### PR TITLE
Update `swc_core`

### PR DESCRIPTION
**Pull request by kdy1**
https://swc.rs/docs/plugin/selecting-swc-core

> We modified AST definitions because of with of [Import Attributes proposal(opens in a new tab)](https://github.com/tc39/proposal-import-attributes).

### CODE REVIEW

**Comment by wooorm** [comment]
I sorted the clippy results that new Rust introduced, but your PR still has problems updating swc. Can you resolve those?

**Comment by kdy1** [comment]
Hmm PR is not updating

**Comment by kdy1** [comment]
Can you publish a new version?

**Comment by wooorm** [comment]
of course, working on it

**Comment by wooorm** [comment]
released! https://github.com/wooorm/mdxjs-rs/releases/tag/0.1.15

**Comment by kdy1** [comment]
Thank you!

**Pull request merged**
